### ISSUE TITLE
Build fails with java version 11.0.1-redhat

### ISSUE THREAD

**Issue by chuckb** [Team997Coders/BB2018BallFindingVision#1]
The build fails with above version of JDK installed. When any gradlew task is run, I get the following:

Could not determine java version from '11.0.1-redhat'.

This is probably related to needing the gradle wrapper updated to a later version.

**Comment by jrmihalick** [comment]
I had the same problem and got by the issue by upgrading the gradle wrapper to the current latest version 5.1.1.  However, the build now fails with this error and I am still investigating the cause.  I have other gradle builds on my machine that are using Java 11 and that are using the gradle java plugin, so I am not sure what the issue is yet.

```
gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
org.gradle.api.internal.java.JavaLibrary.<init>(Lorg/gradle/api/artifacts/PublishArtifact;Lorg/gradle/api/artifacts/DependencySet;)V

```

**Update**
To get by the above 'JavaLibrary' error, I changed the version of the  shadow plugin to the latest version, (4.0.3) ```'com.github.johnrengelman.shadow' version '4.0.3'```

**Comment by chuckb** [comment]
Thanks for the reply. I probably will not fix in this repo but have updated the 2019DSHatchFindingVision project to be happy with all the Java 11 nasties. See that project as a sample if you must use Java 11.
